version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./src:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - shop_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - shop_network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - shop_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  shop_network:
    driver: bridge